### PR TITLE
fix: input validations

### LINKED ISSUE #222: New List: Pressing CREATE with an empty list name leads to a silent http error with no feedback to user.

### LINKED ISSUE #262: Rename textbox should be prefilled with previous name

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): closes #222, closes #262

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the new behavior?

Rename List now have the input prefilled.
Add List/Task now refuses whitespace or empty name.

## PR Checklist
Please check if your PR fulfills the following requirements:
- [x] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

### CODE REVIEW

File: src/ToDo/Presentation/Dialogs/RenameListViewModel.cs [hunk 1]
```diff
@@ -1,6 +1,3 @@
 namespace ToDo.Presentation.Dialogs;
 
-public partial class RenameListViewModel
-{
-    
-}
+public partial record RenameListViewModel(TaskList Entity);
```
Comment (Xiaoy312) [inline src/ToDo/Presentation/Dialogs/RenameListViewModel.cs:3]: @dr1rrb there is something weird with this page. i cant seem to bind to "Entity.DisplayName" with ` IState<TaskList> Entity` like you would expect from other page. `<TextBlock Text={Binding Entity} />` would work, but not `.DisplayName`.

Comment (Xiaoy312) [reply src/ToDo/Presentation/Dialogs/RenameListViewModel.cs:3]: Either way this seem to create a cleaner VM
